### ISSUE TITLE
Example code in slides has errors

### ISSUE THREAD

**Issue by larsks** [stv0g/gont#16]
Several of the examples in the slides contain code like this:

```
createHost := func(pos int) (*g.Host. error) {
  return n.AddHost(fmt.Sprintf("h%d", pos))
}

linkHosts := func(a, b *g.Node) error {
  _, err := n.AddRouter(fmt.Sprintf("r%d", pos),
    o.Interface("eth0", a, o.AddressIPv4(10, 0, 0, a.Position, 24),
    o.Interface("eth1", b, o.AddressIPv4(10, 0, 0, b.Position, 24)
  )
  return err
}
```

What is the variable `o`? Where does it come from?

**Comment by stv0g** [comment]
Hi Lars,

Thanks for the note. `o` is actually used as an alias for the `github.com/stv0g/gont/pkg/options` package.
I used it to fit the code onto the slide.

But now that you opened the issue its pretty clear that this is misleading..
I will update the slides accordingly.

Thanks for reporting it :)

**Comment by stv0g** [comment]
Hi @larsks,

I added the missing imports to the examples in the slides.
I also added a little warning about the examples and linked the full examples in the slides to be more clear.

And in general the slides have been overhauled to include some of the recently added features.
