### ISSUE TITLE
Unable to build code using gont

### ISSUE THREAD

**Issue by larsks** [stv0g/gont#17]
I'm trying to compile the following trivial code that uses Gont:

```
package main

import (
	"fmt"

	"github.com/stv0g/gont"
)

func main() {
	n, err := gont.NewNetwork("mynet")
	if err != nil {
		panic(err)
	}

	fmt.Printf("network: %+v\n", n)
}
```

Running `go mod tidy` on the above fails with:

```
go: finding module for package github.com/stv0g/gont
example imports
        github.com/stv0g/gont: module github.com/stv0g/gont@latest found (v1.6.3), but does not contain package github.com/stv0g/gont
```

The slides don't contain any runnable examples, so I'm not sure if I'm doing something wrong or if there's an error in Gont.

**Comment by stv0g** [comment]
You will need to import `github.com/stv0g/gont/pkg`.

I will add the imports to the slides shortly.

Also see here for examples, on how to use it:
- https://github.com/stv0g/gont#examples
- https://github.com/stv0g/cunicu/tree/master/test/e2e

**Comment by stv0g** [comment]
The slides have been enhanced (see #16)
